version: "3"

services:
  search-agg-api:
    build:
      context: .
    restart: on-failure
    ports:
      - "8001:8000"
    depends_on:
      - db
      - rabbitmq
  search-agg-worker:
    build:
      context: ./worker
    restart: on-failure
    depends_on:
      - rabbitmq
      - db
  search-agg-ui:
    build:
      context: ./ui
    ports:
      - "8000:8000"
  rabbitmq:
    image: "rabbitmq:3"
    ports:
      - "5672:5672"
  db:
    image: "postgres:latest"
    ports:
      - "5433:5432"
    #     volumes:
    #       - ~/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=searchdb
      - POSTGRES_USER=searchdbuser
      - POSTGRES_PASSWORD=12345
